apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: linkerd
    git:
      url: https://github.com/giantswarm/linkerd2-upstream
      ref: stable-2.13.x
    includePaths:
    - viz/charts/linkerd-viz/**/*
    - charts/partials/**/*
- path: helm/linkerd-viz/templates
  contents:
  - path: .
    directory:
      path: vendor/linkerd/viz/charts/linkerd-viz/templates
- path: helm/linkerd-viz/charts/partials
  contents:
  - path: .
    directory:
      path: vendor/linkerd/charts/partials
