version: 2.1
orbs:
  architect: giantswarm/architect@4.33.1

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-giantswarm-app-catalog
          context: architect
          executor: "app-build-suite"
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "linkerd-viz"
          persist_chart_archive: true
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/run-tests-with-ats:
          name: execute chart tests
          app-test-suite_container_tag: "0.2.3"
          filters:
            # Do not trigger the job on merge to main.
            branches:
              ignore:
                - main
          requires:
            - push-to-giantswarm-app-catalog
